### ISSUE TITLE
想问下大佬项目的运行顺序是怎样的

### ISSUE THREAD

**Issue by Haveoneriver** [RichardcLee/SRGAN-LYH#1]
没看懂项目中的GEN_LR.py是如何使用的？能指点下么

**Comment by RichardcLee** [comment]
这个脚本包含了一些：插值、加载不同格式图片、图像预处理和增强的函数；
用法你看得看一下代码和注释(主要是由高分辨率图片生成低分辨率图片)；
在CMD下：python GEN_LR.py INPUT_DIR OUTPUT_DIR。

**Comment by RichardcLee** [comment]
至于运行：
首先，准备大量高分辨率图片，然后生成低分辨率图像；
其次，训练模型（使用 python train.py xxxx）；
最后，测试/应用模型 (使用python test.py xxx)。

**Comment by Haveoneriver** [comment]
> 至于运行：
> 首先，准备大量高分辨率图片，然后生成低分辨率图像；
> 其次，训练模型（使用 python train.py xxxx）；
> 最后，测试/应用模型 (使用python test.py xxx)。
但是我在train.py里面没有找到设置LR图像的文件位置啊，希望能指点下，谢谢

**Comment by Haveoneriver** [comment]
但是我在train.py里面没有找到设置LR图像的文件位置啊，希望能指点下，谢谢

**Comment by RichardcLee** [comment]
--train_set_path
